version: '3.2'
services:
  codeshelf-tool-pmd:
    container_name: codeshelf-tool-pmd
    build: .
    volumes:
      - ${PWD}:/src
    environment:
      - WORKING_DIR=/src
      - DRY=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    logging:
      options:
        max-size: "10m"
        max-file: "10"
